### PR TITLE
Fix lists

### PR DESCRIPTION
**Pull request by zeroem**
How about this?

### CODE REVIEW

**Comment by zeroem** [comment]
@eggsby any objections?

**Comment by darkone23** [comment]
@zeroem what you have here is a good solution. I owe you a milkshake

**Comment by darkone23** [comment]
it occurs to me that `type-aware-get-in` is the only version of `get-in` that works with mapstache:

``` clj
(get-in {:a [1 2 3]} [:a 1])
```

``` clj
(get-in (mustached {:a [1 2 3]}) [:a 1])
```

**Comment by zeroem** [comment]
does your milkshake bring all the boys to the yard? because, if not, I may have to look elsewhere :ice_cream:

**Comment by zeroem** [comment]
ARGH

**Comment by zeroem** [comment]
map-indexed is the problem, it returns a list irrespective of what goes into it. just gonna have to find a type aware way of iterating over lists so we get the same type back.

**Comment by zeroem** [comment]
Alright, so I think I have a solution, but it means that a mapstache will behave slightly differently than an actual map.

`(get-in {:a '(1 2 3)} [:a 1])` will return nil because you can't call get on a list. But with mapstache you would be able to.

**Comment by zeroem** [comment]
I guess, once I introduced the type-aware-get-in that was the case.

**Comment by zeroem** [comment]
aaaaand I lied about the solution. booo tests.

**Comment by darkone23** [comment]
We could do something like:

``` clj
(into (empty thing) (map-indexed fn thing))
```

**Comment by zeroem** [comment]
Yeah, that was my original idea, the problem is that:

``` clojure
(into '() '(1 2 3))
=> '(3 2 1)
```

**Pull request merged**
